services:
  mysql:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    container_name: wheel-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 50M
    ports:
      - '8081:80' # 🔥 phpMyAdmin → http://localhost:8081
    depends_on:
      - mysql
  redis:
    image: redis:7
    ports:
      - '6379:6379'
  nats:
    image: nats:2
    ports:
      - '4222:4222'
volumes:
  mysql_data:
